@echo off
setlocal

set RESOURCE_GROUP=rg-cash-book-dev
set API_APP_NAME=cashbookapi-akash-2026
set CLIENT_URL=https://lemon-moss-0924fe500.6.azurestaticapps.net
set MONGODB_URI=mongodb+srv://USER:PASSWORD@cluster0.xxxxx.mongodb.net/cashflow?retryWrites=true^&w=majority
set JWT_SECRET=REPLACE_WITH_LONG_RANDOM_SECRET
set JWT_ACCESS_EXPIRY=15m
set JWT_REFRESH_EXPIRY=7d
set BCRYPT_ROUNDS=10
set RATE_LIMIT_TTL=60
set RATE_LIMIT_MAX=100
set GOOGLE_CLIENT_ID=
set GOOGLE_CLIENT_SECRET=
set GITHUB_CLIENT_ID=
set GITHUB_CLIENT_SECRET=

set API_BASE_URL=https://%API_APP_NAME%.azurewebsites.net

echo Configuring API app settings...
az webapp config appsettings set --resource-group "%RESOURCE_GROUP%" --name "%API_APP_NAME%" --settings NODE_ENV=production PORT=8080 MONGODB_URI="%MONGODB_URI%" JWT_SECRET="%JWT_SECRET%" JWT_ACCESS_EXPIRY="%JWT_ACCESS_EXPIRY%" JWT_REFRESH_EXPIRY="%JWT_REFRESH_EXPIRY%" CLIENT_URL="%CLIENT_URL%" CORS_ORIGIN="%CLIENT_URL%" BCRYPT_ROUNDS="%BCRYPT_ROUNDS%" RATE_LIMIT_TTL="%RATE_LIMIT_TTL%" RATE_LIMIT_MAX="%RATE_LIMIT_MAX%" GOOGLE_CLIENT_ID="%GOOGLE_CLIENT_ID%" GOOGLE_CLIENT_SECRET="%GOOGLE_CLIENT_SECRET%" GOOGLE_CALLBACK_URL="%API_BASE_URL%/api/auth/google/callback" GITHUB_CLIENT_ID="%GITHUB_CLIENT_ID%" GITHUB_CLIENT_SECRET="%GITHUB_CLIENT_SECRET%" GITHUB_CALLBACK_URL="%API_BASE_URL%/api/auth/github/callback"

echo Done.
echo API Base URL: %API_BASE_URL%
echo Client URL: %CLIENT_URL%

endlocal
